(function(){'use strict';var h;function aa(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var l=aa(this),ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},p;
if("function"==typeof Object.setPrototypeOf)p=Object.setPrototypeOf;else{var r;a:{var ca={a:!0},t={};try{t.__proto__=ca;r=t.a;break a}catch(a){}r=!1}p=r?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var w=p;
function x(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(w)w(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.la=b.prototype};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var da=this||self;function y(a,b,c,d){a="translate3d("+a+"px, "+b+"px, "+c+"px)";d&&(a="rotate3d(0, 1, 0, "+d+"deg) "+a);return a}function z(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a};var A=["-ms-","-moz-","-webkit-",""];function B(a,b,c,d){d=void 0===d?!1:d;for(var e,k,f=0;f<A.length;f++)e=A[f]+b,k=(d?A[f]:"")+c,a.style.setProperty(e,k)};function C(a,b){B(a,"transition","transform "+b+"ms",!0)};function D(a,b){return window.setTimeout(a,b)};function E(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d}function ea(a,b){b=void 0===b?null:b;var c=void 0===c?null:c;D(function(){var d=E("autoplayended",a,b);c&&c(d)},1)}function fa(a,b){function c(d){a.removeEventListener("attached",c);b(d)}a.addEventListener("attached",c)}function ha(a){var b=!1,c=null;return function(){b=!0;c||(b&&(a(),b=!1),c=D(function(){c=null;b&&(a(),b=!1)},250))}};function F(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function G(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")}function ia(a){if(G(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&G(a))return a;return null}
function H(a,b,c,d){d=(void 0===d?"":d)||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)}function ja(a){return(a=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):"")?a.split(",").map(function(b){return b.trim()}):[]};function I(a){this.g=a}I.prototype.toString=function(){return this.g.toString()};I.prototype.i=!0;I.prototype.h=function(){return this.g.toString()};var J;try{new URL("s://g"),J=!0}catch(a){J=!1}var ka=J,la={};function K(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;c++)if(!/^[\s\xa0]*$/.test(a[c])){var d=b,e=d.push;var k=a[c];k=k.trim();k=window.Enabler?window.Enabler.getUrl(k):k;var f=document.createElement("gwd-image");f.setAttribute("source",k);e.call(d,f)}}return b}function L(a,b){for(var c=0;c<a.length;c++){var d=a[c];"gwd-image"==d.tagName.toLowerCase()&&(null!=b?d.setAttribute("scaling",b):d.removeAttribute("scaling"))}}function M(a,b){return"left"==a||"backwards"==a?-b:b}
function N(a,b){return(a%b+b)%b};function ma(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval}function O(a,b){this.g=a;this.h=null;this.j=b;this.i=!1}
function P(a,b,c){c=void 0===c?"forwards":c;if(a.g.frameCount&&null==a.h){var d=a.g.frameCount;b/=d;for(var e=[],k=ma(a.g),f=k,g=0;g<d;g++){if(0<g||!a.j)f=N(f+M(c,1),a.g.frameCount);e.push(f)}c=function(){if(e.length){var n=e.shift();a.i=!0;a.g.goToFrame(n+1);a.i=!1;E("frameautoplayed",a.g,{id:n+1})}else Q(a,!0),a.g.goToFrame(k+1)};a.h=window.setInterval(c,b);setTimeout(c,1)}}function Q(a,b){b=void 0===b?!1:b;!a.i&&a.h&&(window.clearInterval(a.h),ea(a.g,{completed:b}),a.h=null)};var na=["pause-front-media","resume-next-media"];function R(){var a=HTMLElement.call(this)||this;a.i=[];a.g=null;a.h=0;a.u=1;a.B=new O(a,!0);a.O=!1;a.R=!1;return a}x(R,HTMLElement);h=R.prototype;h.attributeChangedCallback=function(a,b,c){switch(a){case "pause-front-media":this.O="true"==c;break;case "resume-next-media":this.R="true"==c}};h.gwdIsLoaded=function(){return!0};h.gwdLoad=function(){};h.goToFrame=function(a,b){this.stopRotation();0!=this.h&&(a>this.h?a=this.h:1>a&&(a=1),this.W(a,b))};
h.W=function(a){this.g=a-1};function S(a,b,c,d){if(null!=a.g){var e=a.u;e=N(a.g+M(b,void 0===e?1:e),a.u*Math.ceil(a.h/a.u));!d&&("forwards"==b&&e<a.g||"backwards"==b&&e>a.g)||a.goToFrame(e+1,c)}}h.goBackwards=function(a,b){S(this,"backwards",void 0===a?"slide":a,void 0===b?!0:b)};h.goForwards=function(a,b){S(this,"forwards",void 0===a?"slide":a,void 0===b?!0:b)};h.rotateOnce=function(a,b){P(this.B,void 0===a?0:a,b)};h.stopRotation=function(){Q(this.B)};
h.getFrame=function(a){if(0!=this.h)return this.i[a-1]};function T(a,b){if(null!=a.g&&a.g!=b){if(a.O)for(var c=Array.prototype.slice.call(a.i[a.g].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),d=0;d<c.length;d++){var e=c[d];e.pause&&e.pause()}if(a.R)for(a=Array.prototype.slice.call(a.i[b].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),b=0;b<a.length;b++)c=a[b],c.play&&c.play()}}
h.Z=function(a){var b=a.length;a=a.splice(0,b);for(var c=0;c<b;c++){var d=a[c];"frameshown"==d?E(d,this,{id:this.currentIndex}):E(d,this)}};l.Object.defineProperties(R.prototype,{currentIndex:{configurable:!0,enumerable:!0,get:function(){return 0<this.h?this.g+1:void 0}},frameSnapInterval:{configurable:!0,enumerable:!0,get:function(){return this.u}},frameCount:{configurable:!0,enumerable:!0,get:function(){return this.h}}});
l.Object.defineProperties(R,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return na}}});var oa="autoplay exit-urls transition-duration frame-width frame-height neighbor-rotation-y neighbor-translation-x neighbor-translation-y neighbor-translation-z start-frame show-reflection has-navigation navigation-highlight navigation-thumbnails images scaling pause-front-media resume-next-media".split(" ");
function U(){var a=R.call(this)||this;a.G=!1;a.m=null;a.L=-1;a.I=0;a.o=null;a.V=a.ha.bind(a);a.U=a.ia.bind(a);a.T=a.ga.bind(a);a.S=a.fa.bind(a);a.F=E.bind(null,"firstinteraction",a);a.N=a.ea.bind(a);a.P=ha(a.Y.bind(a));a.J=!1;a.H=[];a.s=a.Z.bind(a,a.H);a.D=[];a.K=0;a.v=!1;a.j=null;a.C=0;a.B=new O(a,!1);a.l=null;a.M=!1;a.A=!1;return a}x(U,R);h=U.prototype;
h.connectedCallback=function(){if(!this.A){if(this.v=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);var a=document.createElement("gwd-gesture");a.className="gesture";this.o=a;this.A=!0}a=this.o;this.C=this.C||this.clientWidth/2;a.addEventListener("trackstart",this.V,!1);a.addEventListener("track",this.U,!1);a.addEventListener("trackend",this.T,!1);a.addEventListener("tap",this.S,!1);this.addEventListener("transitionend",this.s,!1);this.addEventListener("webkitTransitionEnd",
this.s,!1);this.gwdIsLoaded()||((a=ia(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad());this.M&&V(this);window.addEventListener("resize",this.P,!1)};
h.disconnectedCallback=function(){window.removeEventListener("resize",this.P,!1);var a=this.o;a.removeEventListener("trackstart",this.V,!1);a.removeEventListener("track",this.U,!1);a.removeEventListener("trackend",this.T,!1);a.removeEventListener("tap",this.S,!1);this.removeEventListener("transitionend",this.s);this.removeEventListener("webkitTransitionEnd",this.s)};
h.attributeChangedCallback=function(a,b,c,d){switch(a){case "images":this.v=!0;this.h=0;this.g=null;this.i=K(c||"");V(this);break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":this.A&&W(this);break;case "scaling":L(this.i,c);break;case "pause-front-media":case "resume-next-media":R.prototype.attributeChangedCallback.call(this,a,b,c,d);break;default:X(this)}};h.W=function(a,b){b="none"!=b;var c=this.j.transitionDuration;T(this,a-1);Y(this,b?c:0);Z(this,a-1)};
h.rotateOnce=function(a,b){P(this.B,(void 0===a?0:a)||this.j.transitionDuration*this.h,b)};h.gwdIsLoaded=function(){return this.G};h.gwdLoad=function(){if(!this.G&&!this.m){if(this.v)var a=K(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.i=a;V(this)}};
function V(a){if(a.A){for(;a.firstChild;)a.removeChild(a.firstChild);a.l=null;a.m&&a.m.removeEventListener("pageload",a.N,!1);for(var b=a.i,c=document.createElement("gwd-page"),d=0;d<b.length;d++){var e=b[d];B(e,"user-select","none");e.classList.add("frame");c.appendChild(e)}fa(c,c.gwdLoad.bind(c));a.m=c;c.className=a.hasAttribute("show-reflection")?"container reflection":"container";c.addEventListener("pageload",a.N,!1);L(a.i,a.getAttribute("scaling"));a.appendChild(c);a.appendChild(a.o)}else a.M=
!0}h.ea=function(a){this.m===a.target&&(this.G=!0,this.h=this.i.length,this.D=[],this.K=this.h,pa(this),this.h&&this.j.autoplay&&D(this.rotateOnce.bind(this),0),W(this),E("allframesloaded",this),E("ready",this))};function pa(a){qa(a);if(a.h){var b=a.j.ja-1;if(0>b||b>=a.h)b=0;Y(a,0);Z(a,b)}}h.Y=function(){this.C=this.clientWidth/2;pa(this)};
function qa(a){X(a);for(var b=0,c,d=0;d<a.i.length;d++)c=a.i[d],c.style.left=b+"px",c.style.width=a.j.frameWidth+"px",c.style.height=a.j.frameHeight+"px",b+=a.j.frameWidth}
function X(a){var b=a.i;var c=z(a,"frame-width",Math.floor(.8*a.clientWidth));var d=a.hasAttribute("show-reflection"),e=z(a,"frame-height",d?Math.floor(4*a.clientHeight/7):Math.floor(6*a.clientHeight/7)),k=z(a,"neighbor-translation-x",Math.floor(c/8));if(a.hasAttribute("neighbor-translation-x")){a:{var f=c,g=!0;a.hasAttribute("clamp-frame-size-to-image")&&(c=a.getAttribute("clamp-frame-size-to-image"),"true"==c?g=!0:"false"==c&&(g=!1));if(g)if(c=a.hasAttribute("scaling")?a.getAttribute("scaling"):
"contain",g="contain"==c,!g&&"none"!=c||0==f||0==e)b=f;else{c=-1;for(var n=b.length,u=0;u<n;u++){var m=b[u];if("img"!=m.tagName.toLowerCase()&&"gwd-image"!=m.tagName.toLowerCase()){b=f;break a}var q=m.assetWidth?m.assetWidth:m.naturalWidth;m=m.assetHeight?m.assetHeight:m.naturalHeight;if(0<q&&0<m){var v;g?v=q/m<f/e?q/m*e:f:v=q;c=Math.max(c,v)}}b=-1!=c?Math.min(f,c):f}else b=f}c=b}b=z(a,"neighbor-translation-y",-Math.floor(e/10));v=z(a,"neighbor-translation-z",-e);f=z(a,"neighbor-rotation-y",38);g=
z(a,"start-frame",2);u=e;a.l&&(u-=36);e=ja(a);n=a.hasAttribute("autoplay");q=parseInt(a.getAttribute("transition-duration"),10);isNaN(q)&&(q=600);a.j={autoplay:n,aa:e,frameWidth:c,frameHeight:u,ba:f,ca:k,X:b,da:v,transitionDuration:q,ka:d,ja:g}}h.ha=function(){null!=this.g&&(this.stopRotation(),this.I=this.g,Y(this,0))};h.ia=function(a){if(this.h){this.F&&(this.F(),this.F=null);a=-a.dx/this.j.frameWidth;var b=Math.round(a);ra(this,this.I+b,a-b)}};
h.ga=function(){if(null!=this.g){Y(this,this.j.transitionDuration);var a=this.g;Z(this,a);this.I!=a&&(0==a?E("reachleftend",this):a==this.h-1&&E("reachrightend",this))}};
h.fa=function(a){if(this.h){var b=null;var c=this.o;var d=this.m,e=a.clientX,k=a.clientY,f=c.style["pointer-events"];c.style["pointer-events"]="none";e=d.ownerDocument.elementFromPoint(e,k);c.style["pointer-events"]=f;if(c=e&&F(d,e)?e:null){d=a.clientX;a=a.clientY;f=!1;"gwd-taparea"===c.tagName.toLowerCase()&&(f=c.ownerDocument.createEvent("Event"),f.initEvent("action",!0,!0),f.clientX=d,f.clientY=a,f=!c.dispatchEvent(f));if(f)return;for(a=0;a<this.h;a++)if(F(this.i[a],c)){b=a;break}if(null!=b&&(a=
this.j.aa[b])&&!E("frameexit",this,{url:a}).detail.handled){if(a instanceof I)var g=a;else if(a instanceof I)g=a;else{a="object"==typeof a&&a.i?a.h():String(a);b:if(c=a,ka){try{g=new URL(c)}catch(n){g="https:";break b}g=g.protocol}else c:{g=document.createElement("a");try{g.href=c}catch(n){g=void 0;break c}g=g.protocol;g=":"===g||""===g?"https:":g}"javascript:"===g&&(a="about:invalid#zClosurez");g=new I(a,la)}da.open(g instanceof I&&g.constructor===I?g.g:"type_error:SafeUrl","")}}null==b&&(b=null!=
this.g?this.g:0);E("frametap",this,{element:this.i[b],id:b+1})}};function Y(a,b){a.J=0<b;a.m&&C(a.m,b);for(var c=0;c<a.h;c++)C(a.i[c],b)}function Z(a,b){a.i[b]&&(a.g=b,ra(a,b,0,a.h),a.H.push("frameshown"),a.D[b]||(a.D[b]=!0,--a.K||a.H.push("allframesviewed")));a.J||a.s()}
function ra(a,b,c,d){d=void 0===d?1:d;for(var e=a.j,k,f,g=-d;g<=d;g++)if((k=a.i[g+b])&&0<=c*g){0>g?f=1-Math.abs(c):0<g?f=Math.abs(c)-1:(T(a,b),a.g=b,f=c);var n=Math.abs(f);k.style.setProperty("transform",y(e.ca*f,e.X*n,e.da*n,e.ba*f))}a.L!=a.g&&null!=a.g&&(a.L=a.g,E("frameactivated",a,{id:a.currentIndex}));a.m.style.setProperty("transform",y(a.C-(b+c+.5)*e.frameWidth,-e.X,0))}
function W(a){var b=a.hasAttribute("has-navigation"),c=!!a.l;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.l=document.createElement("gwd-gallerynavigation"),a.l.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.l)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.l),a.l=null);a.l&&(H(a,"navigation-highlight",a.l,"highlight"),H(a,"navigation-thumbnails",a.l,"use-thumbnails"));qa(a)}
l.Object.defineProperties(U,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return oa}}});customElements.define("gwd-carouselgallery",U);}).call(this);
