(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.lockup = function() {
	this.initialize(img.lockup);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Tween11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#636466").s().p("AgTAcQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIACABIACAAIACABQADAAACgCIAEgFIABgFIgBgFIgMgbIgEgGIAOAAIAAACIABADIAHAWIAJgVIABgDIAAgDIAIAAQgCABgBAEIgRAlIgDAGIgEAFIgEADIgGABQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAAAg");
	this.shape.setTransform(46.2,-1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#636466").s().p("AgFAdIABgDIAAgDIAAgDIAAgBIAAgmIAAgBIAAAAIAAgCIgBgGIAKAAIAAAvIAAABIAAAAIAAADIABADIAAADg");
	this.shape_1.setTransform(43.6,-2.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#636466").s().p("AgRAdIAAgGIAAgDIAAAAIAAgBIAAgkIAAgBIAAAAIAAgDIAAgGIAKAAIAAAFIAFgEQACgBAEAAIAGABIAEAEIADAGIABAIQAAAFgBAEQgBADgDAEQgCACgEACQgDACgEgBIgEAAIgDgBIAAAHIAAABIAAAAIAAADIABAGgAgEgUQgCADgBACIAAADIAAAHIAAACIAAAHIABADIACACIAEABIADgBIACgEIACgEIABgHIgBgHIgBgEIgDgDQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAAAgBABQgBAAAAAAQgBAAAAABQgBAAAAAAg");
	this.shape_2.setTransform(40.5,-1.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#636466").s().p("AgRAdIAAgGIAAgDIAAAAIAAgBIAAgkIAAgBIAAAAIAAgDIAAgGIAKAAIAAAFIAFgEQACgBAEAAIAGABIAEAEIADAGIABAIQAAAFgBAEQgBADgDAEQgCACgEACQgDACgEgBIgEAAIgDgBIAAAHIAAABIAAAAIAAADIABAGgAgEgUQgCADgBACIAAADIAAAHIAAACIAAAHIABADIACACIAEABIADgBIACgEIACgEIABgHIgBgHIgBgEIgDgDQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAAAgBABQgBAAAAAAQgBAAAAABQgBAAAAAAg");
	this.shape_3.setTransform(36.2,-1.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#636466").s().p("AgJAUIgDgCIgDgCIAAgEQAAgDACgDQACgCAFgDIAJgEIACgDIABgCIAAgFIgDgDIgDgBIgCABIgCADIgBACIgCADIgCABIgDgBIgCgDIACgEIADgCIAFgCIAFgBQAEAAAFACIAFACIABAGIAAADIAAASIAAAAIAAABIAAADIAAACIAAADIgKAAIAAgFQgCADgEACQgCABgDAAIgEgBgAAAACQgDACgCADIgBADQAAABABAAQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIACgBIADgDIABgEIAAgJIgGADg");
	this.shape_4.setTransform(32,-1.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#636466").s().p("AgHAVIgGgCIAAgHIAGADQADACADAAQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAIgBgEIgDgDIgEgDIgHgFQgCgCAAgEIABgEIADgEIAFgDIAFAAIAGAAIAEABIABAAIABAHIgCgBIgFgCIgEgCQgBAAAAABQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAAAABQgBAAAAABQAAAAAAAAQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAIAGAFIAFADIACABIACAEIAAADIgBAGQgBACgCABQgCACgDABIgGABIgGAAg");
	this.shape_5.setTransform(26.1,-1.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#636466").s().p("AAHAVIAAgJIAAgHIAAgHIAAgGIgBgEQgCgCgEAAIgCABIgCADIgCACIAAAFIAAABIAAAIIAAAFIAAABIABAJIgMAAIABgGIAAgBIAAgCIAAgBIAAgUIAAgBIAAgDIAAgDIgBgDIALAAIAAAFIAFgEIAHgCIAGACIAEADIABAFIAAAFIAAADIAAAHIAAAFIAAABIAAABIAAADIABAGg");
	this.shape_6.setTransform(22.3,-2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#636466").s().p("AgHAUQgEgBgCgDIgEgGIgCgHIAAgCQAAgEACgEIADgHQADgDAEgCQAEgBAEAAQAEAAAEABIAGAEQACADACAEQABAEAAAEQAAAEgBAEIgFAHQgCADgEACQgDABgFAAQgDAAgEgBgAgDgPIgDACIgBAEIgBAGIAAACIABAHIABAGIADAEIAEABIADgBIADgDIACgFIAAgHIAAgGIgCgGIgEgEIgDgBIgDABg");
	this.shape_7.setTransform(17.9,-1.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#636466").s().p("AgFAcIABgGIAAgCIAAAAIAAgBIAAgVIAAgBIAAgCIAAgEIgBgDIAKAAIAAAfIAAABIAAAAIAAACIAAAGgAgDgSQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAAAQABAAABAAQAAABAAAAQABAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAIgDgCg");
	this.shape_8.setTransform(14.7,-2.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#636466").s().p("AgCAZQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAIgBgEIAAgBIAAgDIAAgYIgEAAIAAgEIAEAAIAAgIIAJgEIAAAMIAHAAIgBAEIgGAAIAAAXIAAABQAAABAAABQAAAAAAABQABAAAAABQAAAAAAAAQAAABABAAQAAAAAAABQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBIAAAGIgFABIgEABQgCABgCgCg");
	this.shape_9.setTransform(12.7,-2.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#636466").s().p("AgFAcIABgGIAAgCIAAAAIAAgBIAAgVIAAgBIAAgCIAAgEIgBgDIAKAAIAAAfIAAABIAAAAIAAACIAAAGgAgDgSQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAIgDgCg");
	this.shape_10.setTransform(10.7,-2.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#636466").s().p("AgJAcIgEgEIgEgGIgBgJQAAgEACgFQABgDADgDQACgDAEgBQADgCADAAQADAAAFACIAAgJIAAgBIAAAAIgBgDIAAgFIAKAAIAAAvIAAABIAAAAIABADIAAAFIgLAAIAAgFQgCADgCACIgGABIgGgBgAgCgHIgCADIgCAEIgBAHIAAABIABAHIACAEIACADIACABQADAAACgCQACgCAAgDIABgHIAAgGIgBgDIAAgBQAAgBAAgBQAAgBAAAAQAAgBgBAAQAAgBgBAAQAAAAgBgBQAAAAgBgBQAAAAgBAAQAAAAgBAAIgDABg");
	this.shape_11.setTransform(7.6,-2.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#636466").s().p("AAHAVIAAgJIAAgHIAAgHIAAgGIgCgEQgCgCgCAAIgDABIgCADIgCACIAAAFIAAABIAAAIIAAAFIAAABIABAJIgMAAIABgGIAAgBIAAgCIAAgBIAAgUIAAgBIAAgDIAAgDIAAgDIAKAAIAAAFIAFgEIAGgCIAHACIADADIADAFIAAAFIAAADIAAAHIAAAFIAAABIAAABIAAADIAAAGg");
	this.shape_12.setTransform(3.3,-2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#636466").s().p("AgHAUQgDgBgDgDIgEgGIgCgHIAAgCQAAgEABgEIAFgHQADgDADgCQAEgBADAAQAFAAADABIAHAEQADADAAAEQACAEAAAEQAAAEgCAEIgDAHQgDADgEACQgEABgEAAQgEAAgDgBgAgDgPIgDACIgCAEIAAAGIAAACIAAAHIACAGIAEAEIACABIAFgBIACgDIABgFIABgHIgBgGIgBgGIgDgEIgEgBIgDABg");
	this.shape_13.setTransform(-1.2,-1.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#636466").s().p("AgEAUIgFgFQgDgDgBgEQgBgDAAgFQAAgEABgDIAEgHQADgDADgCQADgBAEAAIAGAAIACABIACAAIAAAHIgEgDIgEAAIgFABIgCACIgCAFIAAAGIAAAGIADAFIACAEIAEAAQADAAAEgBIACgCIgBAFIgGAEIgGABIgGgBg");
	this.shape_14.setTransform(-5.1,-1.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#636466").s().p("AgJAcIgEgEIgEgGIgBgJQABgEABgFQABgDADgDQACgDADgBQAEgCADAAQADAAAFACIAAgJIAAgBIAAAAIgBgDIAAgFIAKAAIAAAvIAAABIAAAAIABADIAAAFIgLAAIAAgFQgCADgCACIgFABIgHgBgAgCgHIgCADIgCAEIgBAHIAAABIABAHIACAEIACADIACABQADAAADgCQABgCAAgDIABgHIAAgGIgBgDIAAgBQAAgBAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAgBgBQAAAAgBgBQAAAAgBAAQAAAAgBAAIgDABg");
	this.shape_15.setTransform(-11.4,-2.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#636466").s().p("AAHAVIAAgJIAAgHIAAgHIAAgGIgCgEQgBgCgDAAIgDABIgCADIgCACIAAAFIAAABIAAAIIAAAFIAAABIABAJIgMAAIABgGIAAgBIAAgCIAAgBIAAgUIAAgBIAAgDIAAgDIAAgDIAKAAIAAAFIAFgEIAGgCIAHACIADADIACAFIAAAFIAAADIAAAHIAAAFIAAABIAAABIAAADIABAGg");
	this.shape_16.setTransform(-15.7,-2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#636466").s().p("AgJAUIgEgCIgCgCIAAgEQAAgDACgDQACgCAFgDIAJgEIACgDIABgCIAAgFIgDgDIgDgBIgCABIgCADIgBACIgCADIgCABIgEgBIgBgDIABgEIAEgCIAFgCIAFgBQAEAAAFACIAFACIABAGIAAADIAAASIAAAAIAAABIAAADIAAACIAAADIgKAAIAAgFQgDADgDACQgBABgEAAIgEgBgAAAACQgDACgCADIgBADQAAABABAAQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIACgBIADgDIABgEIAAgJIgGADg");
	this.shape_17.setTransform(-19.8,-1.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#636466").s().p("AgHAVIgFgCIgBgHIAGADQADACADAAQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAIgBgEIgDgDIgEgDIgHgFQgCgCAAgEIABgEIADgEIAFgDIAEAAIAHAAIAEABIABAAIABAHIgCgBIgFgCIgEgCQgBAAAAABQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQABABAAAAQABABAAAAIAGAFIAEADIADABIACAEIAAADIAAAGQgCACgCABQgCACgDABIgGABIgGAAg");
	this.shape_18.setTransform(-25.7,-1.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#636466").s().p("AATAVIAAgKIAAgHIAAgMIgCgEQgBgBAAAAQgBAAAAAAQgBgBAAAAQgBAAgBAAIgDABIgDACIgBACIAAAEIAAADIAAAGIAAAHIAAABIAAAFIABAEIgLAAIABgEIAAgCIAAgDIAAgBIAAgEIAAgCIAAgDIAAgEIAAgGQAAgBAAAAQgBgBAAgBQAAAAAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAQgBAAgBAAIgDABIgDACIgBAGIAAADIAAAHIAAAGIAAABIAAADIABAGIgMAAIABgDIAAgBIAAgCIAAgDIAAgBIAAgUIAAgBIAAgDIAAgDIAAgDIAKAAIAAAEQADgCADgBQADgCADAAQAEAAACACIAEAEQADgDADgBQADgCAEAAIAFABIAEACIACAEIABAFIAAAFIAAAIIAAAGIAAABIAAADIAAACIABAEg");
	this.shape_19.setTransform(-30.7,-2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#636466").s().p("AgKAVIABgGIAAgCIAAgBIAAgVIAAgBIAAgCIgBgHIAKAAIAAAHIAFgGQACgCADAAIABAAIgBAFIAAAGIgFgCQgBAAAAAAQgBAAAAABQgBAAAAAAQgBABAAAAIgBAHIAAAOIAAAAIAAABIAAACIAAAGg");
	this.shape_20.setTransform(-34.9,-2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#636466").s().p("AgFAUIgGgEQgDgDgBgEQgBgEAAgEQAAgEABgEQACgEACgDQADgDADgBQAEgCADAAQADAAACACIAFACIAEAFIABAFQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgDAAIgRAAIgBAEIABAGIACAEIADADIAFABIAGgBIAGgEIgCAHQgDACgDACIgIABQgDAAgDgBgAgCgOQgCACgBAFIAIAAIADgBIABgCQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgCAAgCACg");
	this.shape_21.setTransform(-38.3,-1.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#636466").s().p("AgFAdIABgKIAAgrIgHAAIgFABIgHABIABgGIAtAAIABAGIgCgBIgKgBIgHAAIAAArIABAKg");
	this.shape_22.setTransform(-42.7,-2.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#636466").s().p("AgDAOIACgLIgIAHIgEgGIALgEIgLgCIAEgGIAIAHIgCgMIAGAAIgBAMIAIgIIADAGIgKADIAKAEIgDAGIgIgHIABALg");
	this.shape_23.setTransform(-46.7,-4.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-94.6,-7.6,189.4,11.4);


(lib.Tween9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AASArIgEgOIgEgNIgFgQIgFgRIgJAgIgIAcIgQAAIgDgOQgCgNgKgnIgDgIIgEgLIAVAAIAAABIABAKIACAGIABACIADAQIADAMIAEAPIAAABIABAEIAMgoQACgJABgHQAAgGgCgFIAUAAIgBAFQAAAGACAHIACAHIAAABIANApIACgIIACgKIACgIIAHgYIABgKIgCgHIAOAAIgCAGIgCAFIgBAGIAAABIgHAaIgHAXIgEASg");
	this.shape.setTransform(27.6,-25.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgJArIgHgCIgHgDIgHgHIgFgGIgEgIIgCgHIgBgJIABgJIACgIIAEgIIAFgHIAHgFIAHgEIAJgCIAIgBIAJABIAIACIAHAEIAGAFIAGAHIADAHIACAIIABAJIgBAJIgCAIIgEAIIgFAGIgHAGIgHAEIgJACIgIABIgJgBgAgKgiQgEACgDAFQgDAFgCAHQgCAHABAIQAAAIABAHQACAHAEAGQADAFAEACQAFADAEAAQAFAAAFgDQAEgCADgFQAEgFACgHQABgGAAgJQAAgIgBgHQgCgHgEgGQgDgFgEgCQgFgDgFAAQgFAAgFADg");
	this.shape_1.setTransform(17.1,-25.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAXArIgxhCIAAAwIAAACIABACIAAADIAAAGIACAFIgMAAIABgFIABgGIAAgFIAAgCIAAgyIgCgLIgBgGIASAAIAtA+IAAgsIAAgBIAAgBIAAgFQAAgGgCgFIAMAAIgBALIAAAFIAAACIAABDg");
	this.shape_2.setTransform(8,-25.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AARArIgGgBQgDgBgDgEIgVgiIAAAWIAAABIAAABIAAADQAAAGACAHIgUAAIABgKIAAgFIAAgBIAAgzIAAgCIAAgDIgBgNIATAAQgBAHAAAHIAAACIAAABIAAABIAAAUIADgDIAGgGIAIgLIACgCIAEgFIADgFIABgFIAAgBIASAAIgDADIgIAIIgFAFIgBACIgQASIAXAhIAKALIAGAFg");
	this.shape_3.setTransform(-2.7,-25.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgJArIgHgCIgHgDIgGgHIgGgGIgEgIIgDgHIAAgJIAAgJIADgIIAEgIIAFgHIAGgFIAIgEIAIgCIAIgBIAJABIAJACIAHAEIAHAFIAEAHIAEAHIADAIIAAAJIAAAJIgDAIIgEAIIgFAGIgGAGIgIAEIgJACIgIABIgJgBgAgJgiQgFACgDAFQgDAFgCAHQgCAHAAAIQAAAIADAHQABAHADAGQADAFAFACQAFADAEAAQAFAAAFgDQAFgCACgFQAEgFACgHQABgGAAgJQAAgIgBgHQgCgHgEgGQgCgFgFgCQgFgDgFAAQgFAAgEADg");
	this.shape_4.setTransform(-11.6,-25.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgJArIgHgCIgHgDIgHgHIgFgGIgEgIIgCgHIgBgJIABgJIACgIIAEgIIAFgHIAHgFIAHgEIAIgCIAIgBIAJABIAJACIAHAEIAHAFIAEAHIAEAHIACAIIABAJIgBAJIgCAIIgEAIIgFAGIgHAGIgHAEIgJACIgIABIgJgBgAgKgiQgEACgDAFQgDAFgCAHQgBAHAAAIQAAAIACAHQABAHADAGQADAFAFACQAEADAFAAQAFAAAFgDQAEgCADgFQAEgFACgHQABgGAAgJQAAgIgBgHQgCgHgEgGQgDgFgEgCQgFgDgFAAQgFAAgFADg");
	this.shape_5.setTransform(-21.2,-25.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgKAsIgUAAIABgGIAAgLIAAgBIAAgxIAAgBIAAgBIAAgCQAAgIgBgGIAHAAIAPgBIAJgBIAEAAIAJABQAEABADADQACACACADQACADgBAEIgBAHIgDAGIgGAFIgIAEIAKACIAHAEQADADACAEQACAEAAAFIgBAIIgFAHIgGAGIgHADIgMACgAgMAbIAAAAIABAHIABADIAHABQADAAAEgCQACgBADgCIAEgGQABgEABgEQgBgFgBgDQgBgDgDgDQgDgDgDgBIgKgBIgFAAgAgMgGIACABQAFAAAEgCQADgBADgCIAEgFQABgDAAgEIgBgGIgDgFIgGgCIgGgBIgBAAIgDAAIgCAAg");
	this.shape_6.setTransform(-29.5,-25.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#846A4C").ss(1.5,1,1).p("AnBh8IODAAQAyAAAAAyIAACVQAAAygyAAIuDAAQgyAAAAgyIAAiVQAAgyAyAAg");
	this.shape_7.setTransform(0,-24.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#002569").s().p("AnBB9QgyAAAAgyIAAiVQAAgyAyAAIODAAQAyAAAAAyIAACVQAAAygyAAg");
	this.shape_8.setTransform(0,-24.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-51,-38.1,102,27);


(lib.Tween7 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#636466").s().p("AgLAfIgIgCIgCgMQAEAEAGACQAFACAEAAQADAAADgCQACgCAAgDQAAgDgCgDIgFgFIgGgEQgIgDgDgEQgCgEAAgFIABgHIAFgGIAGgDQAFgCADAAIAKACIAFAAIACAAIACAKIgDgCIgHgDIgHgBQgCAAgCACQgDACAAADQAAADADADIAJAHIAHAEIAEADIADAFIABAGQAAAEgCAEQgBADgEADQgEACgEABQgFACgEAAIgJgBg");
	this.shape.setTransform(67.3,34.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#636466").s().p("AgIAdQgFgCgEgEQgEgEgCgGQgCgGAAgGQAAgGACgGQACgGAEgFQAEgEAFgCQAGgCAFgBQAEABAEABIAIAFIAFAHQACADAAAEQAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAIgDABIgcAAIAAAGIABAJQABADADADQACAEACABQADACAEgBQAFAAAFgBIAJgHIgDAKQgFAEgFACQgFACgGAAQgFAAgFgCgAgEgWQgDAEgBAGIAMAAIAGgBQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgEgCgDQgDgCgDAAQgEAAgDADg");
	this.shape_1.setTransform(61.9,34.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#636466").s().p("AgQAfIABgIIAAgEIABgCIAAgfIgBgCIAAgEIgBgIIAQAAIAAAJQADgFAEgDQAEgDAEAAIACAAIgCAHIgBAJQgEgDgDAAQgDAAgDADQgBAEAAAGIAAAVIAAABIAAABIAAAEIABAIg");
	this.shape_2.setTransform(57.5,34.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#636466").s().p("AgOAfIgFgDIgDgFQgBgCAAgDQAAgFADgEQADgDAIgEIAOgIIADgDIAAgEIAAgHQAAgDgCgBQgCgCgDAAQgCAAgCACQgDABAAADIgBAEQAAAAgBABQAAAAAAABQAAAAgBAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQgBAAAAAAQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAgBgBAAQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgDACgCQACgDADgCIAIgDIAIgBQAGAAAIADQAEABACADQABADAAAFIAAAFIAAAbIAAABIAAAAIAAAFIABAEIAAAEIgQAAIAAgHQgDAEgEACQgEADgFAAIgGgBgAAAADQgFADgCAEQgBACAAADQAAAEACACQACADAEAAIAEgCQACgBABgDIABgGIAAgOIgIAFg");
	this.shape_3.setTransform(52.3,34.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#636466").s().p("AgOAsIABgMIAAgpIgGAAIAAgGIAGAAIAAgIQAAgFABgEQACgDADgDIAHgEIAJgBIAGABIAFABIgEAIQgEgDgDAAQgFAAgBADQgCAEAAAFIAAAJIALAAIAAAGIgLAAIAAApIAAAFIAAADIABAEg");
	this.shape_4.setTransform(48.5,33.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#636466").s().p("AALAfIAAgNIAAgLIAAgKIgBgKQAAgDgCgDQgDgCgEAAIgEABIgFADIgBAFIgBAHIAAACIAAALIAAAJIAAABIABANIgRAAIABgIIAAgDIAAgCIAAgBIAAggIAAgBIAAgEIAAgFIgBgDIAQAAIAAAGQAEgEAFgCQAEgCAFAAQAFAAAEACQAEACACACQACAEABAFIAAAGIAAAGIAAAKIAAAIIAAACIAAAAIAAABIAAAFIABAIg");
	this.shape_5.setTransform(39.7,34.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#636466").s().p("AgQAfIABgIIAAgEIABgCIAAgfIgBgCIAAgEIgBgIIAQAAIAAAJQADgFAEgDQAEgDAEAAIACAAIgCAHIgBAJQgEgDgDAAQgDAAgDADQgBAEAAAGIAAAVIAAABIAAABIAAAEIABAIg");
	this.shape_6.setTransform(35,34.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#636466").s().p("AgOAdIgGgCQgDgDgBgDIgBgHIAAgBIAAgGIAAgXIAAAAIAAgBIAAgEIgBgJIAQAAIAAAlIAAAHQABAEACACQADACAEAAIAEgBIAEgCIACgEIABgFIAAgEIAAgWIAAgBIAAgCIAAgCIgBgJIAQAAIAAAtIAAABIAAABIAAAEIAAAFIABADIgPAAIAAgHQgEAFgFABQgEADgGAAQgEAAgDgCg");
	this.shape_7.setTransform(29.5,35);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#636466").s().p("AgEAmQgDgCgBgDIgBgGIAAAAIAAgHIAAgjIgHAAIAAgGIAHAAIAAgNIAPgFIgBASIAKAAIgBAGIgJAAIAAAjIAAABQAAAFACACQAAABAAAAQABABAAAAQABAAAAAAQABAAABAAQADAAADgCIgBAIQgDABgEABIgHABQgDABgDgCg");
	this.shape_8.setTransform(24.7,34.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#636466").s().p("AgIAdQgFgCgEgEQgEgEgCgGQgCgGAAgGQAAgGACgGQACgGAEgFQAEgEAFgCQAGgCAFgBQAEABAEABIAIAFIAFAHQACADAAAEQAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAIgDABIgcAAIAAAGIABAJQABADADADQACAEACABQADACAEgBQAFAAAFgBIAJgHIgDAKQgFAEgFACQgFACgGAAQgFAAgFgCgAgEgWQgDAEgBAGIAMAAIAGgBQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgEgCgDQgDgCgDAAQgEAAgDADg");
	this.shape_9.setTransform(20.1,34.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#636466").s().p("AgQAfIABgIIAAgEIABgCIAAgfIgBgCIAAgEIgBgIIAQAAIAAAJQADgFAEgDQAEgDAEAAIACAAIgCAHIgBAJQgEgDgDAAQgDAAgCADQgCAEAAAGIAAAVIAAABIAAABIAAAEIABAIg");
	this.shape_10.setTransform(15.6,34.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#636466").s().p("AALAfIAAgNIAAgLIAAgKIgBgKQAAgDgCgDQgDgCgEAAIgFABIgEADIgBAFIgBAHIAAACIAAALIAAAJIAAABIABANIgRAAIABgIIAAgDIAAgCIAAgBIAAggIAAgBIAAgEIAAgFIgBgDIAQAAIAAAGQAEgEAFgCQAEgCAFAAQAFAAAEACQAEACACACQACAEABAFIAAAGIAAAGIAAAKIAAAIIAAACIAAAAIAAABIAAAFIABAIg");
	this.shape_11.setTransform(6.7,34.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#636466").s().p("AgIAqIABgIIAAgDIAAgBIAAgCIAAgfIAAgBIAAgBIAAgEIAAgEIgBgEIAPAAIAAAtIAAABIAAABIAAAEIABAIgAgFgbQgDgCAAgEQAAgDADgDQADgCACAAQAEAAACACQADADAAAEQAAADgDACQgCADgEAAQgDAAgCgDg");
	this.shape_12.setTransform(2.1,33.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#636466").s().p("AgTAFIAFgJIAiAAIgFAJg");
	this.shape_13.setTransform(-1.5,34.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#636466").s().p("AgIArIABgEIAAgEIAAgEIAAgCIAAg5IAAgCIAAgBIAAgDIgBgIIAPAAIAABHIAAABIAAAAIAAAFIAAAEIABAEg");
	this.shape_14.setTransform(-5.2,33.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#636466").s().p("AgIArIABgEIAAgEIAAgEIAAgCIAAg5IAAgCIAAgBIAAgDIgBgIIAPAAIAABHIAAABIAAAAIABAFIAAAEIAAAEg");
	this.shape_15.setTransform(-8,33.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#636466").s().p("AAVArIgBgFIgEgMIgBgBIgIgTIgZAAIgHATQgDAKAAAEIAAAEIgOAAIADgFIACgGIADgFIAAgCIATgxQADgIAAgEIgBgGIARAAIAOAiIAEAIIAKAXIALAUgAAFAAIgLgbIgKAbIAVAAg");
	this.shape_16.setTransform(-13.4,33.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#002569").s().p("AgLAnQgHgDgFgFQgFgGgCgIQgDgHAAgJQAAgJADgHQACgIAFgGQAGgGAGgDQAHgDAIAAQAGAAAFACQAGACAEAEQAEAEADAFQACAFAAAGQAAADgEAAIgFAAIglAAIAAAJQAAAGACAGQABAFADAFQADADADACQAEADAGAAQAFAAAHgEQAHgCAFgGIgEAOQgGAFgHADQgGADgIAAQgHAAgHgDgAgFgdQgFAFgBAJIARAAQAFAAACgCQACgCAAgDQAAgFgDgEQgDgCgFAAQgFgBgEAFg");
	this.shape_17.setTransform(66.4,-29.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#002569").s().p("AgVAqQACgGAAgGIAAgFIAAgCIAAgqIAAgCIAAgFIgCgMIAVAAIAAAMQAEgGAGgFQAFgEAFAAIACAAIgCAKIgBAMQgGgEgEAAQgEAAgDAEQgCAFAAAIIAAAdIAAABIAAABIAAAFIABAMg");
	this.shape_18.setTransform(60.4,-29.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#002569").s().p("AgOAoQgIgDgFgFQgFgFgDgGQgDgIAAgIIgBgEQAAgJADgHQADgIAFgHQAFgFAIgDQAIgEAHABQAJAAAIACQAHADAGAFQAEAGADAHQADAIAAAKQAAAJgDAIQgDAHgFAHQgFAFgIAEQgHACgJAAQgHABgHgDgAgHgfIgFAEQgCAEgCAEIgCAMIAAADQABAIABAHIAEAMQADAFAEADQADADADAAQAFAAACgCQADgCADgEIADgKIABgNQAAgHgCgHQgBgHgCgFQgCgFgEgDQgEgCgDAAIgHACg");
	this.shape_19.setTransform(52.9,-29.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#002569").s().p("AgkA5IACgLIAAgGIAAgBIAAgBIAAhKIAAgBIAAgBIAAgFIgBgMIAVAAIAAALQAFgGAFgDQAFgDAGAAQAHAAAGADQAFADAEAFQAEAFACAHQACAHAAAJQAAAKgDAHQgCAJgGAGQgFAGgGADQgIADgHAAIgIgBIgHgDIAAAPIAAACIAAAAIABAGIABALgAgJgoQgEAEgBAGIAAAGIgBANIAAAEQAAANABADIABAEQACADADACQADABAEAAQADAAAEgCIAFgGIAEgLIABgNIgBgNQgBgGgDgEQgCgEgDgCQgDgCgDAAQgFAAgEAEg");
	this.shape_20.setTransform(44,-27.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#002569").s().p("AgTApQgEgCgCgCQgDgDgCgDQgBgEAAgEQAAgGAEgFQAEgFAKgEIAUgLQADgCAAgCIABgGIAAgJQgBgDgDgCQgCgDgEAAQgDAAgDACQgDACgBADIgBAGQgBADgCABQgDACgDAAQgEAAgDgCQgCgCAAgDQAAgEACgDQADgEAEgCQAFgDAGgBQAGgBAFAAQAHAAALADQAGACACAEQACADAAAHIAAAHIAAAkIAAABIAAABIAAAGIABAFIAAAGIgVAAIAAgKQgEAGgGADQgFADgHAAQgEAAgEgBgAAAADQgHAFgDAFQgCADAAAEQAAAFADADQADADAFAAQACAAAEgCQADgCACgDQABgDAAgFIAAgTQgFADgGADg");
	this.shape_21.setTransform(35.7,-29.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#002569").s().p("AgUA5IgMgEQgFgDgCgDQgDgEAAgEQAAgGAFgFQAFgGAJgFIgIgEQgCgCAAgEQAAgEAFgDQAFgCAKgCIgJgDIgHgGIgEgHQgBgEAAgFQAAgHACgFQACgFAFgEQAEgEAGgCQAHgCAHAAIADABIAIAAIAKABIAUAAIAAAIIgPAAIAFAIQACAEAAAEIgCAJIgEAIQgEAEgFACQgFADgGACIgGACIgIACQgBAAAAABQAAAAgBAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAAAABQAAAAABAAQAAAAAAABIAHABIACABIAOADIATAEQAFACADADQACADAAAFQAAAFgDAFQgEAFgGAEQgLAHgHACQgMADgGAAQgIAAgGgCgAgUAaQgDADAAAEQAAADACADIAFAFQADADAEABIAJABIAIgBIAIgEIAFgFQACgDAAgCQAAgFgFgBIgDgBIgFgBIgWgFQgFACgDADgAgLgtQgDAFAAAIIAAADQABAIAEAFQADAFAGAAQAFAAAEgFQADgEAAgIIgBgJQgBgEgCgDIgFgEIgFgCQgGAAgDAFg");
	this.shape_22.setTransform(28,-27.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#002569").s().p("AAPApIAAgRIAAgOIgBgPIAAgMQAAgFgEgDQgDgDgGAAQgDAAgDABQgDACgDADIgCAFIgBAKIAAADIAAAPIAAALIAAACQAAAMACAFIgXAAQACgFAAgGIAAgCIAAgEIAAgCIAAgqIAAgCIAAgFIAAgGIgBgGIAUAAIAAAJQAGgFAGgDQAGgCAHAAQAGAAAFACQAGACADAFQADAEAAAHIAAAIIAAAHIAAAPIAAAKIAAACIAAABIAAABIAAAGIACALg");
	this.shape_23.setTransform(19.6,-29.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#002569").s().p("AgLA4IACgLIAAgEIAAgCIAAgCIAAgqIAAAAIAAgCIAAgFIgBgGIgBgGIAVAAIAAA9IAAACIAAABIAAAFQAAAHABAEgAgHgkQgEgEAAgEQAAgFAEgDQADgDAFAAQAEAAAEADQADAEAAAEQAAAFgDADQgEADgFAAQgEAAgDgDg");
	this.shape_24.setTransform(13.5,-30.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#002569").s().p("AgUA6IgSgGIABgPQAIAHAIADQAIADAIAAQAFAAADgBQAEgBADgDIAEgGQACgEAAgEQAAgEgCgDQgBgEgEgDIgDgCIgPgKIgIgEIgIgFIgHgHIgDgIIgBgIQAAgHACgGQADgGAFgEQAGgEAHgCQAHgDAIAAQAJAAALADIAFABIAGAAIABAPQgIgFgHgDQgHgDgHAAIgHABIgGAEQgDACgBAEQgCADAAAEQAAAEACAEQADAEAEADIAOAKQAOAHAHAFQAEADACAGQADAFAAAGQAAAHgEAHQgDAHgGAEQgGAFgJADQgIADgJAAQgHAAgHgCg");
	this.shape_25.setTransform(7.3,-30.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#002569").s().p("AgKAtIAHgkIgcAXIgMgVIAjgLIgjgKIAMgTIAbAWIgHglIAWAAIgGAlIAcgYIALAUIgjAMIAiAMIgNATIgZgXIAGAkg");
	this.shape_26.setTransform(78.3,-9.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#002569").s().p("Ag2C2QgYgHgRgMQgSgNgJgSQgKgSAAgVQAAgPAFgOQAFgPAKgMQAKgNARgMQAQgMAYgOQgRgJgNgJQgNgLgJgMQgJgLgFgMQgEgNAAgNQAAgSAJgQQAIgPAQgMQAQgLAWgGQAWgGAYAAQAZAAAVAFQAUAGAPAKQAPAKAHAOQAIANAAARQAAAMgEAKQgEAMgIALQgIALgMAKIgbAVQAVALAQALQAPAKAKAOQALANAFAOQAFAOAAAQQAAAXgLAVQgKAUgSAQQgTAPgZAJQgZAIgbAAQgcAAgYgHgAgnAXQgLAJgHALQgGAKgEALQgDALAAAMQAAAPAFANQAFAMAJAKQAJAIAMAFQANAGAOAAQANAAANgGQAMgEAKgJQAJgJAFgLQAFgNAAgNQAAgPgGgNQgFgMgKgJQgJgJgSgMQgQgLgOgHgAgSidQgJAEgIAGQgHAHgEAIQgEAJAAAKQAAAJAEAJQAFAJAIAJQAdAYAWALQARgPAKgTQAJgTAAgRQAAgKgEgJQgDgJgHgHQgHgGgKgEQgJgDgMAAQgKAAgKADg");
	this.shape_27.setTransform(56.3,3.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#002569").s().p("Ag2C2QgYgHgRgMQgSgNgJgSQgKgSAAgVQAAgPAFgOQAFgPAKgMQAKgNARgMQAQgMAYgOQgRgJgNgJQgNgLgJgMQgJgLgFgMQgEgNAAgNQAAgSAJgQQAIgPAQgMQAQgLAWgGQAWgGAYAAQAZAAAVAFQAUAGAPAKQAPAKAHAOQAIANAAARQAAAMgEAKQgEAMgIALQgIALgMAKIgbAVQAVALAQALQAPAKAKAOQALANAFAOQAFAOAAAQQAAAXgLAVQgKAUgSAQQgTAPgZAJQgZAIgbAAQgcAAgYgHgAgnAXQgLAJgHALQgGAKgEALQgDALAAAMQAAAPAFANQAFAMAJAKQAJAIAMAFQANAGAOAAQANAAANgGQAMgEAKgJQAJgJAFgLQAFgNAAgNQAAgPgGgNQgFgMgKgJQgJgJgSgMQgQgLgOgHgAgSidQgJAEgIAGQgHAHgEAIQgEAJAAAKQAAAJAEAJQAFAJAIAJQAdAYAWALQARgPAKgTQAJgTAAgRQAAgKgEgJQgDgJgHgHQgHgGgKgEQgJgDgMAAQgKAAgKADg");
	this.shape_28.setTransform(26.5,3.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#002569").s().p("Ag2C2QgYgHgRgMQgSgNgJgSQgKgSAAgVQAAgPAFgOQAFgPAKgMQAKgNARgMQAQgMAYgOQgRgJgNgJQgNgLgJgMQgJgLgFgMQgEgNAAgNQAAgSAJgQQAIgPAQgMQAQgLAWgGQAWgGAYAAQAZAAAVAFQAUAGAPAKQAPAKAHAOQAIANAAARQAAAMgEAKQgEAMgIALQgIALgMAKIgbAVQAVALAQALQAPAKAKAOQALANAFAOQAFAOAAAQQAAAXgLAVQgKAUgSAQQgTAPgZAJQgZAIgbAAQgcAAgYgHgAgnAXQgLAJgHALQgGAKgEALQgDALAAAMQAAAPAFANQAFAMAJAKQAJAIAMAFQANAGAOAAQANAAANgGQAMgEAKgJQAJgJAFgLQAFgNAAgNQAAgPgGgNQgFgMgKgJQgJgJgSgMQgQgLgOgHgAgSidQgJAEgIAGQgHAHgEAIQgEAJAAAKQAAAJAEAJQAFAJAIAJQAdAYAWALQARgPAKgTQAJgTAAgRQAAgKgEgJQgDgJgHgHQgHgGgKgEQgJgDgMAAQgKAAgKADg");
	this.shape_29.setTransform(-3.4,3.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#002569").s().p("Ag2C2QgYgHgRgMQgSgNgJgSQgKgSAAgVQAAgPAFgOQAFgPAKgMQAKgNARgMQAQgMAYgOQgRgJgNgJQgNgLgJgMQgJgLgFgMQgEgNAAgNQAAgSAJgQQAIgPAQgMQAQgLAWgGQAWgGAYAAQAZAAAVAFQAUAGAPAKQAPAKAHAOQAIANAAARQAAAMgEAKQgEAMgIALQgIALgMAKIgbAVQAVALAQALQAPAKAKAOQALANAFAOQAFAOAAAQQAAAXgLAVQgKAUgSAQQgTAPgZAJQgZAIgbAAQgcAAgYgHgAgnAXQgLAJgHALQgGAKgEALQgDALAAAMQAAAPAFANQAFAMAJAKQAJAIAMAFQANAGAOAAQANAAANgGQAMgEAKgJQAJgJAFgLQAFgNAAgNQAAgPgGgNQgFgMgKgJQgJgJgSgMQgQgLgOgHgAgSidQgJAEgIAGQgHAHgEAIQgEAJAAAKQAAAJAEAJQAFAJAIAJQAdAYAWALQARgPAKgTQAJgTAAgRQAAgKgEgJQgDgJgHgHQgHgGgKgEQgJgDgMAAQgKAAgKADg");
	this.shape_30.setTransform(-33.2,3.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#002569").s().p("AgHCRIAAgYIgJAAQgLAAgQgEQgPgEgUgIIACgdIALAIQANAJAPAFQAPAFANAAQAIAAAIgDQAIgDAFgGQAHgFACgHQAEgHAAgIQAAgJgEgHQgDgHgHgGIgGgEIgggUIgQgKQgKgFgHgGQgIgHgFgHQgFgIgCgIQgDgIAAgJQAAgMAFgLQAFgLAJgJQAJgJAMgEQAMgFAMAAIAEAAIAAgaIATAAIAAAZIAJAAQAHAAARADQAOADAHAAIAEAfQgRgLgOgGQgOgFgOAAQgJAAgHACQgHADgFAFQgGAEgDAHQgDAGAAAIQAAAIAEAJQAFAIAKAHQAJAHAUAMQAbAPAPAKQAIAIAFALQAFALAAALQAAANgFALQgFAMgIAJQgJAJgNAHQgMAGgPADIAAAbg");
	this.shape_31.setTransform(-56.8,-3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#002569").s().p("AgqB2QgQgFgUgIIACgdQAPAMASAHQAQAIAPgBQAKAAAHgCQAJgDAGgFQAGgGADgHQADgHAAgIQAAgIgDgIQgEgHgGgFIgHgFIgfgUIgQgJQgKgGgIgGQgHgHgGgHQgFgHgCgJQgDgHAAgKQABgOAFgMQAGgLALgJQALgIAPgEQAPgFAQAAQASAAAXAFIAKACIALAAIADAfQgPgLgPgFQgOgGgOAAQgJAAgHACQgHADgGAFQgFAEgDAHQgDAGgBAJQABAHAEAJQAFAIAKAHQAJAHAUAMQAbAPAOAKQAJAIAEALQAFALABALQgBAQgGANQgIANgMALQgNAKgQAEQgRAGgTAAQgNAAgQgDg");
	this.shape_32.setTransform(-74.4,-3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#002569").s().p("AgOApIgMgDIgDgPQAGAFAIADQAIADAFAAQAEAAADgDQADgDAAgEQAAgEgDgEQgBgDgGgDIgHgFQgLgGgDgFQgEgFgBgHQABgFACgEQACgFAEgDQAEgDAFgBQAGgCAFAAIANABIAHACIACgBIACANIgDgCQgFgDgFgBIgIgBQgFAAgCACQgDADAAAEQAAAEADAEQADAEAJAFIAKAGIAFAEQADACABAEQACAEAAAEQAAAGgDAFQgCAEgEADQgFAEgHACQgGABgGAAIgLgBg");
	this.shape_33.setTransform(64.7,-53.2);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#002569").s().p("AgOApIgMgDIgDgPQAGAFAIADQAIADAFAAQAEAAADgDQADgDAAgEQAAgEgDgEQgBgDgGgDIgHgFQgLgGgDgFQgEgFgBgHQABgFACgEQACgFAEgDQAEgDAFgBQAGgCAFAAIANABIAHACIACgBIACANIgDgCQgFgDgFgBIgIgBQgFAAgCACQgDADAAAEQAAAEADAEQADAEAJAFIAKAGIAFAEQADACABAEQACAEAAAEQAAAGgDAFQgCAEgEADQgFAEgHACQgGABgGAAIgLgBg");
	this.shape_34.setTransform(58,-53.2);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#002569").s().p("AgTApQgEgCgCgCQgDgDgCgDQgBgEAAgEQAAgGAEgFQAEgFAKgEIAUgLQADgCAAgCIABgGIAAgJQgBgDgDgCQgCgDgEAAQgDAAgDACQgDACgBADIgBAGQgBADgCABQgDACgDAAQgEAAgDgCQgCgCAAgDQAAgEACgDQADgEAEgCQAFgDAGgBQAGgBAFAAQAHAAALADQAGACACAEQACADAAAHIAAAHIAAAkIAAABIAAABIAAAGIABAFIAAAGIgVAAIAAgKQgEAGgGADQgFADgHAAQgEAAgEgBgAAAADQgHAFgDAFQgCADAAAEQAAAFADADQADADAFAAQACAAAEgCQADgCACgDQABgDAAgFIAAgTQgFADgGADg");
	this.shape_35.setTransform(50.7,-53.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#002569").s().p("AgKA6IAAgGIABgGIAAgFIAAgCIAAhNIAAgCIAAgBIAAgFIgBgLIAUAAIAABgIAAABIAAABIAAAFIAAAGIABAGg");
	this.shape_36.setTransform(45.1,-55);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#002569").s().p("AgDA6QgFgBgFgCIgJgFIgIgHIgGgJIgFgKIgDgLIgBgMIABgLIAEgMIAFgKIAGgJIAJgHQAEgEAFgCQAFgCAGgBIAKgBIARABIAGABIADABIADAAIACAAIABAQIgEgDQgGgDgHgCQgGgDgHAAQgHAAgGAEQgGADgEAGQgEAHgDAJQgCAJAAALQAAALACAJQADAJAFAGQAEAHAGADQAHADAIAAIAJgBIAHgCQAFgDAKgKIgFAQQgHAGgJADQgJADgJAAIgKgBg");
	this.shape_37.setTransform(38.2,-54.9);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#002569").s().p("AgoA4QgDgDAAgDQAAgEACgCQADgCADAAIAFAAIAEABIADABQAGAAAEgEQAEgEADgGQADgGAAgFIgBgIIgag4QgDgHgFgFIAeAAIgBADQAAAFACADIAQArIASgpIACgIIgBgFIAQAAQgDADgDAIIgiBKIgGANIgJAKQgEADgFACQgEACgGAAQgGAAgEgCg");
	this.shape_38.setTransform(24.3,-51.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#002569").s().p("AAmApIAAgSIAAgPIAAgaQgBgFgDgDQgEgCgFAAIgHABIgGADIgBAFIgBAIIAAAGIAAAMIAAAPIAAABIAAABIAAAJIABAIIgVAAIABgHIAAgEIABgGIAAgCIAAgJIAAgEIAAgGIAAgIIgBgMQgBgGgDgDQgDgCgGAAIgHABIgFAEQgDAEAAAIIABAGIAAAPIAAAMIAAABIAAAHQAAAGABAFIgXAAIABgFIAAgCIAAgEIAAgGIAAgCIAAgqIAAgBIAAgGIAAgFIAAgBIgBgGIAWAAIAAAIQAFgFAGgCQAGgCAGAAQAIAAAFACQAFADADAFQAHgFAFgDQAHgCAHAAQAGAAAFABIAHAEQADADABAEQACAEAAAGIgBALIAAARIAAAMIAAACIAAAAIAAAGIABAEIABAHg");
	this.shape_39.setTransform(14.3,-53.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#002569").s().p("AgPAoQgGgCgGgGQgFgEgDgIQgDgGgBgJIAAgEQAAgIADgJQADgIAGgGQAEgFAIgDQAHgDAJgBQAJAAAHADQAIADAEAFQAFAGAEAIQACAIAAAJQAAAJgDAIQgDAIgFAFQgFAHgIACQgIADgIABQgHAAgIgDgAgHggIgFAGQgCACgBAGIgCALIAAADQgBAIACAHIAEAMQADAGADACQAEAEADAAQAFAAADgDQADgCACgEIADgJIABgOQAAgHgBgHQgBgHgDgFQgCgEgEgEQgDgCgEAAIgHABg");
	this.shape_40.setTransform(3,-53.2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#002569").s().p("AAPApIAAgRIAAgOIgBgPIAAgMQAAgFgEgDQgDgDgGAAQgDAAgDABQgDACgDADIgCAFIgBAKIAAADIAAAPIAAALIAAACQAAAMACAFIgXAAQACgFAAgGIAAgCIAAgEIAAgCIAAgqIAAgCIAAgFIAAgGIgBgGIAUAAIAAAJQAGgFAGgDQAGgCAHAAQAGAAAFACQAGACADAFQADAEAAAHIAAAIIAAAHIAAAPIAAAKIAAACIAAABIAAABIAAAGIACALg");
	this.shape_41.setTransform(-5.9,-53.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#002569").s().p("AgOAoQgIgCgFgGQgFgEgDgIQgDgGgBgJIAAgEQAAgIADgJQADgIAFgGQAGgFAHgDQAIgDAIgBQAIAAAIADQAHADAGAFQAEAGAEAIQACAIAAAJQAAAJgDAIQgCAIgGAFQgGAHgHACQgIADgIABQgIAAgGgDgAgHggIgFAGQgDACAAAGIgDALIAAADQAAAIACAHIAEAMQACAGAFACQADAEAEAAQADAAADgDQADgCADgEIADgJIABgOQAAgHgCgHQAAgHgDgFQgDgEgDgEQgDgCgEAAIgHABg");
	this.shape_42.setTransform(-14.8,-53.2);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#002569").s().p("AgJAnQgGgDgFgGQgEgFgDgHQgCgIAAgJQAAgIACgIQADgIAFgFQAFgHAHgCQAHgEAHAAIANABIAFABIACAAIAAANIgHgEQgEgBgFgBQgFAAgDACQgDADgDADQgCAEgBAGQgCAGAAAHQAAAGACAGQABAGADAEQACAEADACQAEADAFgBQAHAAAHgDIAEgFIgDANQgFAEgGACQgGACgGAAQgGAAgHgDg");
	this.shape_43.setTransform(-22.7,-53.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#002569").s().p("AglA6IABgFIABgIIAAgHIAAhOIgCgRIBCAAIACANIgFgCQgJgCgMAAIgSAAIAAAqIANAAQAHAAANgEIAAAOIgKgCIgKgBIgNAAIAAAvIAWAAIAQgBIANgDIgGAOg");
	this.shape_44.setTransform(-30.1,-55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-89.2,-62.7,178.5,105.1);


(lib.Tween5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002569").s().p("AhkCYIADgNIACgTIABgUIAAjPQAAgWgFgWICvAAIAFAgIgNgEQgXgGggAAIgwAAIAABvIAiAAQATAAAkgKIAAAoQgOgFgMgCQgOgDgQAAIghAAIAAB9IA8AAQAYAAAQgCQAPgCAVgHIgPAkg");
	this.shape.setTransform(134.3,-7.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#002569").s().p("AhbCYQAGgYAAgYIAAjQIgBgVQgBgPgDgLIBEAAIgCALQgCAMAAATIAADsIAsAAQAUAAASgDQASgDASgHIgNAmg");
	this.shape_1.setTransform(113,-7.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#002569").s().p("ABLCYQgCgMgCgHQgDgLgNgfIgCgDIgchCIhcAAIgYBCQgMAjAAAOIACAPIgzAAIALgUIAJgTIAJgTIACgGQAshtAXhAQAKggAAgNQAAgLgFgKIA+AAIAyB4IAPAgIAjBRQAOAeAaAogAAQAAIgohhIgjBhIBLAAg");
	this.shape_2.setTransform(87.9,-7.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#002569").s().p("Ag3CYQgUgEgagLIADgnQATASAWAIQAWAKAUgBQANAAAJgDQALgEAIgGQAIgHAEgJQAFgKAAgLQAAgLgFgJQgFgKgIgGIgJgGIgpgbIgVgMQgNgGgKgJQgKgIgGgKQgHgKgDgKQgDgLAAgMQAAgSAHgQQAIgPAOgLQAOgKATgGQAUgHAWABQAXgBAeAHIANACIAOABIAEAoQgUgOgTgIQgTgHgSAAQgLABgJADQgKADgHAHQgIAGgDAHQgFAKAAAJQAAALAHAMQAGAKAMAJQAMAKAbAPQAjASASAOQALALAHAOQAGAOAAAPQAAAUgJASQgJARgQANQgQANgWAGQgXAIgYAAQgSAAgUgGg");
	this.shape_3.setTransform(61.8,-7.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#002569").s().p("AgiCYQAGgbgBgZIAAjlIgeAAIgdACQgYACgSAGIAGggID5AAIAGAgIgPgEQghgGgXAAIgfAAIAADlQAAAbAGAZg");
	this.shape_4.setTransform(25.2,-7.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#002569").s().p("ABLCYQgCgMgCgHQgDgLgNgfIgCgDIgchCIhcAAIgYBCQgMAjAAAOIACAPIgzAAIALgUIAJgTIAJgTIACgGQAshtAXhAQAKggAAgNQAAgLgFgKIA+AAIAyB4IAPAgIAjBRQAOAeAaAogAAQAAIgohhIgjBhIBLAAg");
	this.shape_5.setTransform(-1.6,-7.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#002569").s().p("AhkCYIADgNIACgTIABgUIAAjPQAAgWgFgWICvAAIAFAgIgNgEQgXgGggAAIgwAAIAABvIAiAAQATAAAkgKIAAAoQgOgFgMgCQgOgDgQAAIghAAIAAB9IA8AAQAYAAAQgCQAPgCAVgHIgPAkg");
	this.shape_6.setTransform(-26.1,-7.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#002569").s().p("ABiCaQgZAAgHgBQgHgBgKgFQgNgIgTgXIg1hFIgKgOIgIgKIgJgHIgGgFIAABQIAAAGIAAAJIAAAJQAAAUAGATIhHAAIAEgTQADgPAAgWIAAgBIAAgGIAAiuIgBgHIAAgTQAAgSgHgWIA0AAIAkgDIAigBQATAAAQAEQAQAFALAJQALAJAGAMQAGANAAAQQAAAPgFAOQgFANgKAKQgKAMgOAHQgOAJgSAFIBGBcIATAXQAMANARANIAWANgAhFh/IAAB2IALAAQAPABAOgGQANgEAKgJQAJgKAFgMQAFgNAAgOQAAgMgDgLQgEgJgGgIQgHgGgJgEQgKgDgNAAQgPAAgPACg");
	this.shape_7.setTransform(-49.2,-8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#002569").s().p("AgQCbQgQgDgPgFQgOgFgNgIQgMgHgKgKQgLgKgHgMQgJgMgFgNQgGgOgCgQQgDgPAAgRQAAgZAHgZQAGgZANgTQAJgQAPgNQAQgNASgJQATgJAVgFQAUgGAWAAQALAAAeAEIAKACIATACIASACIAIAAIAFAuIgTgNQgRgJgVgFQgVgFgSAAQgYAAgRAGQgPAFgMAMQgMALgJARQgJARgEAUQgFAVAAAXQADAoAEAQQAHAZANASQANARARAJQAKAFAKACIAWACQATAAAhgKIAAhUIAAgTIgEgUIBEAAQgEAMgBAZIAABGIAAAQQAAAKAFAPIgZgCIgUACIggAFQgWAFgYAAQgRAAgQgDg");
	this.shape_8.setTransform(-80.6,-7.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-126,-25,300,64);


(lib.Tween4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#143978").s().p("AiGAPIAAgdIENAAIAAAdg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-13.5,-1.5,27,3);


(lib.Tween3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#143978").s().p("AhZDjIAjhNIgLAAIAAgEIANAAIAKgVIgIAAIAAgFIAKAAIAIgSIgJAAIAAgHIAMAAIAag5IADgRIhoAAQgeAAgOgCIgzA8QgTANgOgBIAfhSIgjgFIAAgHIAjgFIgfhRQAOgCATAOIAzA7QAOgCAeAAIBoAAIgDgQIgag6IgMAAIAAgHIAJAAIgIgSIgKAAIAAgFIAIAAIgKgVIgNAAIAAgEIALAAIgjhNIgJgGIAkACIA+BJIAmAAIAAASIgYAAIAmAuIAqAAIAAARIgaAAIAsA1IABADIBBAAQAdACAOAGQAGACAHAFQADADAAACQAAAEgDACQgIAGgFACQgOAFgdACIhBAAIgBADIgsA1IAaAAIAAASIgqAAIgmAtIAYAAIAAASIgmAAIg+BJIgkACg");
	this.shape.setTransform(0,0,0.633,0.633);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15,-14.7,30,29.6);


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#636466").s().p("AgYAiQgBAAAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgBABAAQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAAAAAIADAAIADABIACAAQAEAAADgCQACgCACgFIABgGIgBgFIgQgjIgEgHIASAAIAAABIABAFIAJAbIAMgaIABgEIgBgDIALAAIgFAGIgUAuIgEAJIgFAGQgDACgDABIgHABQgDAAgCgCg");
	this.shape.setTransform(6.3,1.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#636466").s().p("AgMAZIgEgCIgCgEIgBgEQAAgEACgDQADgDAGgDIAMgGIACgDIABgEIAAgFQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIgBAEIgCACQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIABgFIAEgDIAHgCIAHgBQAEAAAHACIAFADQABADAAAEIAAAEIAAAWIAAABIAAABIAAADIABAEIAAADIgNAAIAAgGQgDADgEACQgCACgEAAIgGgBgAAAACQgEADgCADQAAABAAAAQgBABAAAAQAAABAAABQAAAAAAABQAAADACACQACACADAAIADgCIADgDIABgFIAAgLIgHADg");
	this.shape_1.setTransform(1.7,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#636466").s().p("AgGAkIABgDIAAgEIAAgEIAAgBIAAgvIAAgBIAAgCIAAgCIgBgHIAMAAIAAA7IAAABIAAAAIAAAEIAAAEIABADg");
	this.shape_2.setTransform(-1.8,-1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#636466").s().p("AgWAjIABgHIAAgDIAAAAIAAgBIAAguIAAgBIAAgBIAAgDIgBgHIANAAIAAAGIAHgFQACgBAFgBQAEABADABQAEACACADIAEAIIABAKQAAAGgCAEQgBAFgEAEQgDAEgEACQgEACgFAAIgFAAIgEgCIAAAJIAAABIAAADIABAHgAgFgZQgDACAAAEIgBAEIAAAIIAAAEIABAJIAAACIADADIAFABQAAAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQACgBACgCIACgHIABgIIgBgIIgCgGIgDgEQgBAAAAAAQgBAAAAgBQgBAAgBAAQAAAAAAAAQgDAAgCACg");
	this.shape_3.setTransform(-5.7,1.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#636466").s().p("AgHAYIgHgFQgDgDgCgFQgBgFAAgGQAAgEABgFQACgFADgEQADgDAFgCQAEgCAEAAIAHABIAHAEIAEAFIABAHQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgDAAIgXAAIAAAGIABAHIADAGQABACACABIAGACQAEAAAEgCQAEgCADgDIgCAIQgEAEgEABQgEACgFAAQgEAAgFgCgAgDgSQgDADgBAGIALAAIAEgBIABgEQAAgDgCgCQgCgCgDAAQgCAAgDADg");
	this.shape_4.setTransform(-10.9,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#636466").s().p("AAXAlIgHAAIgEgCQgEgCgEgFIgMgRIgCgDIgCgDIgCgCIgCgBIAAATIAAACIAAACIAAACQAAAFACAFIgRAAIABgFIABgJIAAgCIAAgoIAAgCIAAgEQAAgFgCgEIAMAAIAJgBIAIAAIAHABQAEABADACIAEAFQABADAAAEIgBAGQgBAEgDACIgFAEIgHADIAQAVIAEAGIAHAHIAFADgAgQgeIAAAdIADAAIAHgCQADgBACgCQACgCABgDQABgDAAgDIgBgGIgCgDQAAgBAAAAQgBgBAAAAQAAAAgBgBQgBAAAAAAIgFgBIgIAAg");
	this.shape_5.setTransform(-16,-1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-21.6,-6.6,43.3,13.2);


(lib.replay_btn = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// hit
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AiVCWIAAkrIErAAIAAErg");
	this.shape.setTransform(35,15);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.clickthrough_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape.setTransform(150,125);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


// stage content:
(lib._300x250 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthrough_btn.cursor = "pointer";
		this.clickthrough_btn.on("click", function(){
		  window.open(clickTag, "_blank");
		});
		
		var frequency = 3;
		stage.enableMouseOver(frequency);
	}
	this.frame_120 = function() {
		this.stop()
		this.replay_btn.cursor = "pointer";
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame()
		{
		this.gotoAndPlay(1);
		}
		
		var frequency = 3;
		stage.enableMouseOver(frequency);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(120).call(this.frame_120).wait(6));

	// replay_btn
	this.replay_btn = new lib.replay_btn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(15.8,11.7,1.667,0.833,0,0,0,29.5,14);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replay_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(120).to({_off:false},0).wait(6));

	// clickthrough_btn
	this.clickthrough_btn = new lib.clickthrough_btn();
	this.clickthrough_btn.parent = this;
	this.clickthrough_btn.setTransform(106.5,71.5,1,1,0,0,0,106.5,71.5);
	new cjs.ButtonHelper(this.clickthrough_btn, 0, 1, 2, false, new lib.clickthrough_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthrough_btn).wait(126));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("A3bzhMAu3AAAMAAAAnDMgu3AAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(126));

	// replay
	this.instance = new lib.Tween2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(31.7,16.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(110).to({_off:false},0).to({alpha:1},15).wait(1));

	// tnc
	this.instance_1 = new lib.Tween11("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(150,171.2);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(95).to({_off:false},0).to({startPosition:0},15).wait(16));

	// cta
	this.instance_2 = new lib.Tween9("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(150.1,160.2,0.5,0.5,0,0,0,0.3,0.3);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(89).to({_off:false},0).to({regX:0,regY:0.1,scaleX:1.1,scaleY:1.1,x:150,y:174.2,alpha:1},6).to({regY:0,scaleX:1,scaleY:1,y:171.2},9).wait(22));

	// pp
	this.instance_3 = new lib.Tween7("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(133.3,81.4);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(74).to({_off:false},0).to({alpha:1},15).wait(37));

	// hl
	this.instance_4 = new lib.Tween5("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(126.1,118.1,0.333,0.333,0,0,0,0,0.1);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({regX:0.1,scaleX:1.17,scaleY:1.17,x:122.2,y:117,alpha:1},9).to({regX:0,regY:0,scaleX:1,scaleY:1,x:126.1,y:118.1},10).wait(40).to({startPosition:0},0).to({alpha:0},15).wait(52));

	// plane
	this.instance_5 = new lib.Tween3("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(25,144.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({x:260},19).wait(40).to({startPosition:0},0).to({alpha:0},15).wait(52));

	// line
	this.instance_6 = new lib.Tween4("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(2.6,144.5,0.185,1,0,0,0,0.2,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({scaleX:8.89,x:121.8},19).wait(40).to({startPosition:0},0).to({alpha:0},15).wait(52));

	// lockup
	this.instance_7 = new lib.lockup();
	this.instance_7.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(126));

	// bg
	this.instance_8 = new lib.bg();
	this.instance_8.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(126));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,124,302,252);
// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg.jpg?1536912628118", id:"bg"},
		{src:"images/lockup.png?1536912628118", id:"lockup"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;